services:
  - type: web
    name: shmucks-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    autoDeploy: true
    envVars:
      - fromGroup: shmucks-secrets
